# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77374cd36983f6308f86d46cf29fe16aaa43b1a5596d2804af2fd1f6e6cb8f6ac649b9b6602f2bc448f83ba39ce71132e41d284e60517bc7c4ae9286e239a0f1

test:
  secret_key_base: 5ab899da79d567a4c3c1ebff5d873d11b8a10b32698ed6f672897d36bf0e7c73febfea0575039dee7e8381732750bc0fced06b76e45efaabfc6c77f75cd0066b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
